### ISSUE TITLE
feat: Consider adding functionality to remove a leader key menu

### ISSUE THREAD

**Issue by abeldekat** [abeldekat/lazyvim-menu-addon#1]
```lua
keys_to_remove = { f = "F" }
```

Perhaps: Not necessary. The user can which_key_ignore the menu

**Comment by hoarse-boy** [comment]
very good idea @abeldekat, there are alot of leader key that i want to remove as it is very bloated. manual `vim.keymap.del` is a hassle.

**Comment by abeldekat** [comment]
Closing. This repro will be archived.
